
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1108x685")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 685,
    width = 1108,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
imported_image = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_canvas = canvas.create_image(
    336.0,
    246.0,
    image=imported_image
)

canvas.create_text(
    86.0,
    445.0,
    anchor="nw",
    text="LSB data",
    fill="#FFFFFF",
    font=("Inter", 24 * -1)
)

red_filter_btn_img = PhotoImage(
    file=relative_to_assets("button_1.png"))
red_filter_btn = Button(
    image=red_filter_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
red_filter_btn.place(
    x=770.0,
    y=37.0,
    width=197.0,
    height=53.0
)

green_filter_btn_img = PhotoImage(
    file=relative_to_assets("button_2.png"))
green_filter_btn = Button(
    image=green_filter_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
green_filter_btn.place(
    x=770.0,
    y=129.0,
    width=197.0,
    height=53.0
)

blue_filter_btn_img = PhotoImage(
    file=relative_to_assets("button_3.png"))
blue_filter_btn = Button(
    image=blue_filter_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
blue_filter_btn.place(
    x=770.0,
    y=221.0,
    width=197.0,
    height=53.0
)

gray_code_btn_img = PhotoImage(
    file=relative_to_assets("button_4.png"))
gray_code_btn = Button(
    image=gray_code_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
gray_code_btn.place(
    x=770.0,
    y=313.0,
    width=197.0,
    height=53.0
)

lsb_data_btn_img = PhotoImage(
    file=relative_to_assets("button_5.png"))
lsb_data_btn = Button(
    image=lsb_data_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
lsb_data_btn.place(
    x=86.0,
    y=613.0,
    width=274.0,
    height=35.66033935546875
)

change_image_btn_img = PhotoImage(
    file=relative_to_assets("button_6.png"))
change_image_btn = Button(
    image=change_image_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
change_image_btn.place(
    x=86.0,
    y=37.0,
    width=158.0,
    height=36.0
)

show_original_image_btn_img = PhotoImage(
    file=relative_to_assets("button_7.png"))
show_original_image_btn = Button(
    image=show_original_image_btn_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
show_original_image_btn.place(
    x=428.0,
    y=37.0,
    width=158.0,
    height=36.0
)

canvas.create_rectangle(
    86.0,
    474.0,
    464.0,
    594.0,
    fill="#D9D9D9",
    outline="")
window.resizable(False, False)
window.mainloop()
